name: flutter_crud
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rflutter_alert: ^2.0.2
  transparent_image: ^2.0.0
  timeline_tile: ^2.0.0
  timeline_list: ^0.0.3
  image_picker: ^0.8.1+1
  dio: ^4.0.0
  flutter_image_slideshow: ^0.1.1
  shared_preferences: ^2.0.6 
  firebase_messaging: ^12.0.3
  firebase_core: ^1.2.0
  steps_indicator: ^1.3.0
  intl: ^0.17.0
  flutter_animated_dialog: ^2.0.1
  connectivity_plus: ^1.1.0
  sizer: ^2.0.15
  gscarousel: ^0.0.1
  nextflow_thai_personal_id: ^1.0.2
  titled_navigation_bar: ^4.1.0
  carousel_pro: ^1.0.0
  dotted_border: ^2.0.0+1
  searchable_dropdown: ^1.1.3
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  flutter_svg: ^0.22.0
  provider: ^6.0.2
  skeleton_text: ^3.0.0
  animated_text_kit: ^4.2.1
  # simple_animations: ^4.0.1
  # titled_navigation_bar: ^4.1.0
  custom_bottom_navigation_bar: ^0.0.1
  # custom_navigator: ^0.3.0
  # url_launcher: ^6.0.6  
  # get_it: ^1.0.3+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  geolocator: ^7.2.0+1
  google_maps_flutter: ^2.0.6
  # flutter_launcher_icons: ^0.9.0

# flutter_icons:
  # android: true
  # image_path: "images/logo_app.png"
  
  http:
  flutter_local_notifications:
  url_launcher: ^6.0.6  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  
  permission_handler: ^8.1.4+2

# flutter_native_splash: ^1.0.0
  flutter_native_splash: ^1.0.0

flutter_native_splash: 
  color: "#ffffff"
  image: images/icons.png
  android: true
  ios: true


flutter_icons:
  android: true
  ios: true
  image_path: "images/play_store_512.png"
  adaptive_icon_foreground: "images/play_store_512.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo_twyshop.png
    - images/contact.jpg
    - images/facebook.png
    - images/line.png
    - images/phone.png
    - images/contactfilter.jpg
    - images/icons-h.gif
    - images/logo_twy.png
    - images/icon-warning.png
    - images/icon-warning2.png
    - images/logo_twy_w.png
    - images/delivery-truck.png
    - images/truck.png
    - images/shop.png
    - images/logo_home.png
    - images/line_b.png
    - images/success.png
    - images/load.gif
    - images/load_h.gif
    - images/check.gif
    - images/error_pin.gif
    - images/truck_mark.png
    - images/gif.gif
    - images/warning_s.png
    - images/logo_contact.png
    - images/install_logo.png
    - images/TY.png
    - images/illustration1.png
    - images/into_logo.png
    - images/illustration2.png
    - images/mec_im.png
    - images/logotwy.png
    - images/load_img.gif
    - icons/users.svg

  #   - images/a_dot_ham.jpeg
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Regular.ttf
  #       - asset: fonts/Prompt-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
