org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
# android.enableDexingArtifactTransform=false
android.useFullClasspathForDexingTransform=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.0.4.jdk/Contents/Home
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# รองรับ 16 KB memory page size
android.experimental.enable16kPage=true